feat: sort collection activity
ParasHQ/paras-landing pull request #414
Opened 2022-03-03 15:17 UTC by yuesth

- sort by price, from, to

2022-03-03 20:15 UTC, ahnafalfariza requested changes

2022-03-03 20:15 UTC, ahnafalfariza commented on components/Collection/CollectionActivity.js
> +																}}
untuk `router.push` second argumentsnya apakah perlu? soalnya kalo cek di [docsnya](https://nextjs.org/docs/api-reference/next/router), itukan optional decorator ya, (untuk di show di browser url bar). jadi sepertinya bisa di first argument aja. jadi mungkin bisa gini aja
```js
router.push(
  {
    pathname: `/collection/${collectionId}`,
    query: {
      headerActivities: d.id,
      sortActivities: 'asc',
      tab: `activity`,
    },
  },
  '/collection/${collectionId}'
  { shallow: true, scroll: false }
)
```
wdyt?

2022-03-03 20:15 UTC, ahnafalfariza commented on pages/collection/[collection_id].js
> +				  }
bagian sortActivitiesnya langsung gini, how?
```js
{sortActivities === `asc` ? `::1` : `::-1`}
```

2022-03-03 20:15 UTC, ahnafalfariza commented on components/Collection/CollectionActivity.js
> +																	)
same as above

2022-03-03 20:15 UTC, ahnafalfariza commented on components/Collection/CollectionActivity.js
> +																}}
same as above

2022-03-03 20:15 UTC, ahnafalfariza commented on components/Collection/CollectionActivity.js
> +														}}
same as above

2022-03-04 01:51 UTC, yuesth commented on components/Collection/CollectionActivity.js
> +																}}
woke gan, untuk query `?tab=activity` nya perlu ditambahin gan di 2nd argumentnya?

2022-03-04 01:57 UTC, yuesth commented on pages/collection/[collection_id].js
> +				  }
woke fixing gan

2022-03-04 02:01 UTC, yuesth commented on components/Collection/CollectionActivity.js
> +																	)
fixing gan

2022-03-04 02:01 UTC, yuesth commented on components/Collection/CollectionActivity.js
> +																}}
fixing gan

2022-03-04 02:01 UTC, yuesth commented on components/Collection/CollectionActivity.js
> +														}}
fixing gan

2022-03-04 11:14 UTC, ahnafalfariza approved these changes

2022-03-04 11:15 UTC, merged

2022-03-07 08:16 UTC, yuesth commented
close #430