feat: following and followers (integration API)
ParasHQ/paras-landing pull request #685
Opened 2022-06-14 20:18 UTC by iqbalutomo

2022-06-16 04:15 UTC, ahnafalfariza requested changes

2022-06-16 04:18 UTC, iqbalutomo commented on components/Profile/Profile.js
> +				if (resp) {
done hu

2022-06-16 04:20 UTC, iqbalutomo commented on components/Follow/Follow.js
> +
noted hu

2022-06-16 10:33 UTC, ahnafalfariza reviewed
oiya btw swrnya bisa lu extract jadi hooks aja sih, kalo mungkin bisa reusable di tempat lain. 
 contoh di `useTokenSeries.js`, `useToken.js`, dll

API referencenya: https://swr.vercel.app/docs/options

2022-06-16 10:33 UTC, ahnafalfariza commented on components/Profile/Profile.js
> +	const [dataUpdate, setDataUpdate] = useState(false)
dataUpdate masih dipake ga ini?

2022-06-16 10:33 UTC, ahnafalfariza commented on components/Follow/Follow.js
> +		setFollowers(resProfile.followers)
following sama followers perlu masuk state kah? soalnya harusnya udah ada dari sini
```js
const { data, mutate } = useSWR(userProfile.accountId, fetchProfile)
data.following
data.followers
```

2022-06-16 10:33 UTC, ahnafalfariza commented on components/Follow/Follow.js
> +							onClick={() => actionFollowUnfollow()}
component button gaada props onMouseEnter sama onMouseLeave gan

2022-06-16 10:33 UTC, ahnafalfariza commented on components/Follow/Follow.js
> +	followerAmount,
props2nya bisa di cek lagi ya kira kira masih perlu atau ga, atau mungkin bisa jadi `fallbackData` di options `useSWR`nya

2022-06-16 10:41 UTC, iqbalutomo commented on components/Follow/Follow.js
> +							onClick={() => actionFollowUnfollow()}
noted

2022-06-16 10:42 UTC, iqbalutomo commented on components/Follow/Follow.js
> +	followerAmount,
ok hu

2022-06-16 10:49 UTC, ahnafalfariza commented on components/Follow/Follow.js
> +		setFollowers(resProfile.followers)
data yang dari server dijadiin fallbackData aja kalo gitu gan (sebagai initial), jadi awalnya ngga 0
```jsx
const { data, mutate } = useSWR(userProfile.accountId, fetchProfile, {fallbackData: dataDariSSR})
```

2022-06-16 10:54 UTC, ahnafalfariza commented on components/Profile/Profile.js
> +	const [dataUpdate, setDataUpdate] = useState(false)
okee

2022-06-16 10:59 UTC, iqbalutomo commented on components/Follow/Follow.js
> +		setFollowers(resProfile.followers)
wokeh hu, mantap hu

2022-06-20 09:14 UTC, iqbalutomo commented on components/Follow/FollowList.js
> +
done

2022-06-20 09:50 UTC, ahnafalfariza approved these changes

2022-06-20 09:51 UTC, merged