feat: add reminder
ParasHQ/paras-landing pull request #857
Opened 2022-08-01 11:02 UTC by cryingraven

2022-08-02 07:32 UTC, ahnafalfariza requested changes

2022-08-02 07:32 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
>  	const [tabActive, setTabActive] = useState('story')
seinget gua email ga di exposed di sini, ini datanya dari api `/profiles`. mungkin bisa pakai `isEmailVerified` sih

2022-08-02 07:32 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +							)}
fyi conditionalnya bisa gini sih, sama props `onChange`nya ga perlu di wrap pake anonymous function lagi
```suggestion
							{showRemindMe && data && data.status === 'upcoming' && !isEndedComing && (
								<ReminderCheckbox value={remindMe} onChange={changeRemindMe} />
							)}
```

2022-08-02 07:32 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +			)}
bisa pakai conditional yang `&&` aja daripada elsenya dikasih empty fragment

2022-08-02 07:32 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +				</Modal>
onClose bisa langsung function aja, ga perlu di wrap anonymous function, soalnya functionnya gaperlu arguments kan
```js
  close={closeReminderModal}
```

2022-08-02 07:32 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +
ini `useEffect`nya ga dikasih dependecy props om? soalnya ini bakal ke-run in every render.
[Info](https://beta.reactjs.org/learn/synchronizing-with-effects#step-2-specify-the-effect-dependencies)

2022-08-02 07:52 UTC, cryingraven commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
>  	const [tabActive, setTabActive] = useState('story')
ada email nya om. gue ganti pake showEmailWarning/isEmailVerified  aja

2022-08-02 07:58 UTC, iqbalutomo commented on components/Launchpad/ReminderCheckbox.js
> +		<div className="text-gray-200 mt-6 flex justify-between items-center mt-2">
mt nya double mas, bisa pake yg mt-6 aja

2022-08-02 08:17 UTC, cryingraven commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +							)}
ok

2022-08-02 08:17 UTC, cryingraven commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +				</Modal>
ok

2022-08-02 09:44 UTC, ahnafalfariza commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +	const [showRemindMe, setShowRemindMe] = useState(true)
bagian ini beda mas, `isEmailVerified` sama `showEmailWarning`. `showEmailWarning` bisa false walaupun dia belum verified, soalnya itu buat hide or show warning. https://github.com/ParasHQ/paras-landing/blob/master/components/Nav.js#L140

2022-08-02 11:02 UTC, lionfather commented on pages/mint-calendar/[launchpad_id]/project/[project_id].js
> +	const [showRemindMe, setShowRemindMe] = useState(true)
ok

2022-08-03 03:03 UTC, ahnafalfariza approved these changes

2022-08-04 04:27 UTC, ahnafalfariza approved these changes

2022-08-04 04:37 UTC, iqbalutomo approved these changes

2022-08-04 05:53 UTC, merged